services:
  tsurugi:
    platform: linux/x86_64
    container_name: tsurugi
    image: ghcr.io/project-tsurugi/tsurugidb
    ports:
      - "12345:12345"

    volumes:
      - /opt/tsurugi/var/data/log:/opt/tsurugi/var/data/log
      - ./send:/mnt/client